### ISSUE TITLE
Fallback does not work for `advanced-custom-fields-pro` plugin

### ISSUE THREAD

**Issue by scherii** [2ndkauboy/language-fallback#5]
When I choose «German (Switzerland)» as the main language and «German» as a fallback, [ACF PRO (v5)](http://www.advancedcustomfields.com/pro/) still loads the default English translation file. Other plugins, for example «BackWPup», load the German language file.

As far as I can tell, ACF PRO does this to load the language file:

``` php
load_textdomain( 'acf', acf_get_path( 'lang/acf-' . get_locale() . '.mo' ) );
```

…which should work I suppose :confused:

Is this something that can be fixed in «language-fallback» or by the ACF plugin author?

**Comment by 2ndkauboy** [comment]
I have to take a look at it, but I would assume that is has to be fixed by ACF. Usually a plugin author s should not call the `load_textdomain()` functions directly, but use the `load_plugin_textdomain()` function instead.

I had a similar issue with the MailPoet plugin and just wrote a little helper plugin for a quick fix: https://gist.github.com/2ndkauboy/555a0ae9fb80c2eea56e

But the real issue is the bad initialization of the plugin. It loads too early, so no other plugin has the chance to get their filters applied.

I justed opened a PR on the ACF project to solve the initialization issue: https://github.com/elliotcondon/acf/pull/452

**Comment by scherii** [comment]
Great, thank you! :smiley:

**Comment by 2ndkauboy** [comment]
@scherii Hey, it looks like the issue is now also fixed in the ACF Pro plugin. If you can confirm that, please close this issue.

**Comment by scherii** [comment]
Yes, sorry. Forgot about this issue.

Thank you for your help!
